[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL Token Lending CLI"
edition = "2018"
homepage = "https://spl.solana.com/token-lending"
license = "Apache-2.0"
name = "spl-token-lending-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.1.0"

[dependencies]
clap = "3.2.6"
solana-clap-utils = "1.10.10"
solana-cli-config = "1.10.10"
solana-client = "1.10.10"
solana-logger = "1.10.10"
solana-sdk = "1.10.10"
solana-program = "1.10.10"
spl-token-lending = { path="../program", features = [ "no-entrypoint" ] }
spl-token = { path="../../token/program", features = [ "no-entrypoint" ]  }

[[bin]]
name = "spl-token-lending"
path = "src/main.rs"
